---
title: "amalarski-agora-gpw"
author: "Adam Malarski"
date: "5 maja 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
Dane <- read.csv("C:/Users/Adam/ts-r/cw3/amalarski-agora-gpw.txt")
head(Dane)
Data <- Dane $Data
Date <- as.Date(Data, "%Y-%m-%d")
df<-cbind(df,Date)
Data1<- as.numeric(1:length(Date))
Wolumen <- Dane $Wolumen
Otwarcie <- Dane $Otwarcie
Zamkniecie <- Dane $Zamkniecie

```
## Modele regresji

Wykonam model regresji liniowej dla wszystkich danych.

```{r}
ramka<-data.frame(Date,Otwarcie)
head(ramka)
plot(ramka,'p',col="blue");
regresja <- lm(ramka$Otwarcie~ramka$Date);
plot(regresja);
abline(regresja)
summary(regresja)
```
Dane dzielę na dwa zbióry uczący i testowy
```{r}
moment <- 46
stala <- 30
n <- length(Data1)
zb_uczacy<-data.frame(Data1[(moment-stala):(moment-1)],Otwarcie[(moment-stala):(moment-1)])
zb_testowy<-data.frame(Data1[moment:n],Otwarcie[moment:n])
```
Wykonuję model regresji dla zbioru uczącego
```{r}
regresja_u<-lm(Otwarcie~Data1, data=zb_uczacy)
plot(regresja_u);
abline(regresja_u)
summary(regresja_u)
```
Wykonuję model regresji dla zbioru testowego
```{r}
wspolczynnik=coef(regresja_u)
a=wspolczynnik[2]
b=wspolczynnik[1]
pr=a*zb_testowy$Data1.moment.n. +b
pr
```

```{r}
plot(zb_testowy$Data1.moment.n.,zb_testowy$Otwarcie.moment.n., main = "Prognozowanie", ylab = "Otwarcie", xlab = "Dzień notowań w 2019 roku")
lines(zb_testowy$Data1.moment.n., pr, col="blue")
```

Wyznaczam błąd średniokwadratowy
```{r}
bsk <-mean((pr-zb_testowy$Otwarcie.moment.n.)^2)
bsk
```
i wartość statystyki Theil'a

```{r}
theil <-sum((pr-zb_testowy$Otwarcie)^2)/sum(zb_testowy$Otwarcie^2)
theil
```

 
 