---
title: "cw3_GPW_WOJAS"
author: "Dudaczyk"
date: "28 maja 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
dane <- read.csv("C:/Users/Justyna/Desktop/Madzia/Szeregiczasowe/cw2/dudaczyk-GPW-WOJAS.csv", header=TRUE)[,1:5]

summary(dane)
```

## Including Plots

```{r}
plot(dane$Maksymalna, type="l", main="Maksymalne ceny spółki WOJAS",col="green",xlab = "Data", ylab="Notowania")
axis(1, at = dane$Data, labels = levels(dane$Data))
```
```{r}
plot(dane$Minimalna, type="l", main="Minimalne ceny spółki WOJAS",col="red",xlab = "Data", ylab="Notowania")
axis(1, at = dane$Data, labels = levels(dane$Data))
```
```{r}
plot(dane$Maksymalna, type="l", main="Wykresy cen maksymalnych i minimalnych spółki WOJAS", col="green",xlab = "Data", ylab = "Notowania spółki WOJAS")
lines(dane$Minimalna, type="l", col="red")
axis(1, at = dane$Data, labels = levels(dane$Data))

plot(dane$Otwarcie, type="l", main="Wykresy cen otwarcia i zamknięcia spółki WOJAS", col="blue",xlab = "Data", ylab = "Notowania spółki WOJAS")
lines(dane$Zamkniecie, type="l", col="grey")
axis(1, at = dane$Data, labels = levels(dane$Data))
```
```{r}
plot(dane$Otwarcie, type="l", main="Wykresy notowań spółki WOJAS", col="blue",xlab = "Data", ylab = "Notowania spółki WOJAS")
lines(dane$Maksymalna, type="l", col="green")
lines(dane$Minimalna, type="l", col="red")
lines(dane$Zamkniecie, type="l", col="grey")
axis(1, at = dane$Data, labels = levels(dane$Data))
```

```{r}
# install.packages("quantmod")
library("quantmod")
WOJAS <- xts(dane[, -1], order.by = as.Date(dane[, 1]))
names(WOJAS) = c("WOJ.Open", "WOJ.High", "WOJ.Low", "WOJ.Close")
chartSeries(WOJAS, bar.type = "hlc", TA = NULL, type = "bars")
```
```{r}
chartSeries(WOJAS)
```
```{r}
Data<-dane$Data
Otwarcie<-dane$Otwarcie
```

```{r}
Data2 <- as.Date(Data, "%Y-%m-%d")
dane<-cbind(dane,Data2)
```

```{r}
ramka<-data.frame(Data2,Otwarcie)
head(ramka)
plot(ramka,'p',col="blue");
reg <- lm(Otwarcie~Data2, data=ramka);
plot(reg);
abline(reg)
```

```{r}
summary(reg)
```

```{r}
p=70
zbU=data.frame(cbind(Data2=Data2[1:(p-1)],Otwarcie=Otwarcie[1:(p-1)]))
zbT=data.frame(cbind(Data2=Data2[p:length(Data2)],Otwarcie=Otwarcie[p:length(Otwarcie)]))
```

```{r}
plot(zbU$Data2, zbU$Otwarcie,'p',col="red", main = "Predykcja na zbiorze uczącym", xlab="Dni", ylab="Otwarcie")
```

```{r}
model <- lm(zbU$Otwarcie ~ zbU$Data2)
summary(model)
```

```{r}
plot(zbU$Data2, zbU$Otwarcie,'p',col="red");
abline(model)
```

```{r}
a = model$coefficients[[2]]
b = model$coefficients[[1]]

#model liniowy postaci y = ax + b
predykcja = a * zbT$Data2 + b
plot(zbT$Data2, zbT$Otwarcie, main = "Predykcja dla modelu ", xlab="Dni", ylab="Kursy")
lines(zbT$Data2, predykcja, col= "blue")
```

```{r}
bladsr<- mean((predykcja-zbT$Otwarcie)^2)
theila <- sum((predykcja-zbT$Otwarcie)^2)/sum(zbT$Otwarcie^2)
```

```{r}
bladsr
theila
```