---
title: "Zadanie4"
author: "Ania Szczepaniak"
date: "30 kwietnia 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pobieramy dane:

```{r}
dane<-read.csv('aszczepaniak-data.csv', header = TRUE)
View(dane)
```

Pobieramy pakiet dplyr.

```{r}
library(dplyr)
```

Wykonujemy grupowanie po Wolumen.

```{r}
dane %>%
group_by(dane$Wolumen)%>%
summarise(Najwieksza_liczba = max(Najwyzszy))
```
Rysujemy wykres z danych otrzymanych po grupowaniu.

```{r}
plot(dane$Wolumen, dane$Najwieksza_liczba , type="l")
percentage <- table(dane$Wolumen)
pie(percentage)
```

Następnie 3-krotnie skorzystam z funkcji filter i wyświetlę wyniki na wykresach.

```{r}
dane %>%
filter(dane$Wolumen> 2000, dane$Najwyzszy<2.70, dane$Najnizszy>2.20) -> dane2

plot(dane2$Data, dane2$Wolumen)
hist(table(dane$Najwyzszy<2.70))
percentage <- table(dane2$Wolumen) 
pie(percentage)
boxplot(dane2$Wolumen, dane2$Najwyzszy, dane2$Najnizszy)

```


Teraz 2-krotnie skorzystam z funkcji mutate i również przedstawię wyniki na wykresie.

```{r}
dane %>%
mutate(wieksza_liczba1 = dane$Najwyzszy,dane$Najnizszy) -> dane3
dane3
dane %>%
mutate(wieksza_liczba2 = dane$Otwarcie,dane$Zamkniecie) -> dane4
dane4

hist(table(dane3$wieksza_liczba1))
hist(table(dane4$wieksza_liczba2))
plot(dane3$wieksza_liczba1, dane4$wieksza_liczba2, type = "p")
boxplot(dane3$wieksza_liczba1, dane4$wieksza_liczba2)
```
